import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dean Projekt Gradnja Kalendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" sizes="128x128" href="favicon.ico"></link>
      <body className={inter.className} cz-shortcut-listen='true'>{children}</body>
    </html>
  );
}
